name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    name: Run Linting and Tests

    runs-on: ubuntu-latest

    steps:
    - name: Clone airnode
      uses: actions/checkout@master

    - name: Check hyperlinks
      uses: gaurav-nelson/github-action-markdown-link-check@v1

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: failure()
      with:
        channel: '#technical-notifications'
        commit: true
        job_name: 'Airnode - Documentation'
        token: ${{ secrets.ACCESS_TOKEN }}
        type: ${{ job.status }}
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
